Repository mohamedloul1/project_schoon_maak_bedrijf, pull requests merged in 2022-03, with the labels that each got.

#1 project-page
  app/controllers/project.php
  app/views/includes/navbar.php
  app/views/project/index.php
  public/css/projecten.css
  public/css/projecten.css.map
  public/js/errorName.js
  public/scss/projecten.scss
Labels: enhancement

#2 message-style
  app/controllers/contact.php
  app/views/contact/index.php
  public/css/boxmessage.css
  public/css/boxmessage.css.map
  public/scss/boxmessage.scss
Labels: enhancement

#4 verbeterde actie uitgevoerd
  app/views/pages/overons.php
  app/views/project/index.php
  public/css/home.css
  public/css/home.css.map
  public/css/overons.css
  public/css/overons.css.map
  public/css/projecten.css
  public/css/projecten.css.map
  public/css/whatsapp.css
  public/css/whatsapp.css.map
  public/scss/home.scss
  public/scss/overons.scss
  public/scss/projecten.scss
  public/scss/whatsapp.scss
Labels: documentation

#5 texten toegevoegd
  app/controllers/Pages.php
  app/controllers/contact.php
  app/controllers/dinsten.php
  app/libraries/Core.php
  app/views/dinsten/bouwoplevering.php
  app/views/dinsten/gevelreiniging.php
  app/views/dinsten/glasbewassing.php
  app/views/dinsten/ontruiming.php
  app/views/dinsten/schoonmaak.php
  app/views/dinsten/vloeronderhoud.php
  app/views/home.php
  app/views/includes/contactfoto.php
  app/views/includes/navbar.php
  app/views/pages/contact.php
  app/views/pages/dinsten.php
  app/views/pages/overons.php
  app/views/pages/projecten.php
  public/css/bouwoplevering.css
  public/css/bouwoplevering.css.map
  public/css/contact.css
  public/css/contactfoto.css
  public/css/dinsten.css
  public/css/dinsten.css.map
  public/css/gevelreiniging.css
  public/css/gevelreiniging.css.map
  public/css/glasbewassing.css
  public/css/glasbewassing.css.map
  public/css/home.css
  public/css/home.css.map
  public/css/ontruiming.css
  public/css/ontruiming.css.map
  public/css/overons.css
  public/css/overons.css.map
  public/css/projecten.css
  public/css/projecten.css.map
  public/css/schoonmaak.css
  public/css/schoonmaak.css.map
  public/css/vloeronderhoud.css
  public/css/vloeronderhoud.css.map
  public/img/Home-back.jpg
  public/img/drop-of-water-ge50902774_1920.jpg
  public/img/raspberry-gd366d7ccb_1920.jpg
  public/img/water-g18118a24a_1920.jpg
  public/img/window-cleaner-g4e8bc606d_1920.jpg
  public/js/errorName.js
  public/scss/bouwoplevering.scss
  public/scss/boxmessage.scss
  public/scss/contact.scss
  public/scss/contactfoto.scss
  public/scss/dinsten.scss
  public/scss/gevelreiniging.scss
  public/scss/glasbewassing.scss
  public/scss/home.scss
  public/scss/ontruiming.scss
  public/scss/overons.scss
  public/scss/projecten.scss
  public/scss/schoonmaak.scss
  public/scss/vloeronderhoud.scss
Labels: enhancement

#6 hierbij voeg mijn wijziging
  app/views/home.php
  app/views/includes/navbar.php
  app/views/includes/whatsappicon.php
  app/views/pages/overons.php
  app/views/pages/projecten.php
  app/views/project/index.php
  public/css/bouwoplevering.css
  public/css/bouwoplevering.css.map
  public/css/contact.css
  public/css/contact.css.map
  public/css/dinsten.css
  public/css/dinsten.css.map
  public/css/gevelreiniging.css
  public/css/gevelreiniging.css.map
  public/css/glasbewassing.css
  public/css/glasbewassing.css.map
  public/css/home.css
  public/css/home.css.map
  public/css/main.css
  public/css/main.css.map
  public/css/navbar.css
  public/css/navbar.css.map
  public/css/ontruiming.css
  public/css/ontruiming.css.map
  public/css/overons.css
  public/css/overons.css.map
  public/css/projecten.css
  public/css/projecten.css.map
  public/css/schoonmaak.css
  public/css/schoonmaak.css.map
  public/css/vloeronderhoud.css
  public/css/vloeronderhoud.css.map
  public/css/whatsapp.css
  public/css/whatsapp.css.map
  public/js/errorName.js
  public/scss/home.scss
  public/scss/main.scss
  public/scss/navbar.scss
  public/scss/overons.scss
  public/scss/projecten.scss
  public/scss/root/_colors.scss
Labels: bug
